### ISSUE TITLE
I get this when opening the generated .svg files

### ISSUE THREAD

**Issue by Rotekoppen** [TheDerek/snake-oil#1]
XML-lesefeil: prefix not bound to a namespace
Plassering: file:///C:/Users/Tobias/Desktop/snake-oil-master/assets/cards/0.svg
Linjenummer 15, kolonne 13:            <ns0:image height="15" id="cardImage" width="15" x="29.625" xlink:href="../snake_letter.svg" y="30" ns6:href="snake_letter.svg" />
------------^

translated:
XML-readerror: prefix not bound to a namespace
Placement: file:///C:/Users/Tobias/Desktop/snake-oil-master/assets/cards/0.svg
Line 15, kolonne 13:            <ns0:image height="15" id="cardImage" width="15" x="29.625" xlink:href="../snake_letter.svg" y="30" ns6:href="snake_letter.svg" />
------------^

**Comment by TheDerek** [comment]
Good spot! I was unnecessary adding an extra href to the card nodes, which didn't even have the correct namespace :laughing:. This has been fixed in the latest commit.
